import type { Starter } from '../sheets/types';

// H5 character creation: attributes 4/3/3/3/2/2/2/2/1; a skill distribution
// and three specialties; a Creed and a Drive; 2 Edges and 1 Perk (or 1 Edge
// and 2 Perks); 7 dots of backgrounds and 2 of flaws; Health = Stamina + 3,
// Willpower = Composure + Resolve. Desperation and Danger belong to the cell
// and start low.

export const HUNTERS: Starter[] = [
  {
    key: 'htr-dez-mcallister',
    game: 'hunter',
    sort: 1,
    name: 'Dez McAllister',
    faction: 'Inquisitive',
    portrait: '/portraits/hunter-flannel.webp',
    summary: 'Ex-crime-scene photographer. Keeps the cell’s evidence board and refuses to stop asking questions.',
    sheet: {
      profile: {
        name: 'Dez McAllister',
        concept: 'Crime-scene photographer who saw too much',
        chronicle: 'Glasgow by Night',
        cell: 'The Kelvin Street Cell',
        creed: 'Inquisitive',
        drive: 'Curiosity',
        ambition: 'Prove to the world what is really feeding in the East End.',
        desire: 'One photograph that nobody can explain away.',
      },
      attributes: { Strength: 2, Dexterity: 3, Stamina: 2, Charisma: 2, Manipulation: 2, Composure: 3, Intelligence: 3, Wits: 4, Resolve: 1 },
      skills: {
        Investigation: { dots: 4, specialty: 'Crime scenes' },
        Craft: { dots: 3, specialty: 'Photography' },
        Awareness: { dots: 3, specialty: 'The detail that’s wrong' },
        Technology: { dots: 3 },
        Stealth: { dots: 2 },
        Insight: { dots: 2 },
        Streetwise: { dots: 2 },
        Drive: { dots: 1 },
        Larceny: { dots: 1 },
        Occult: { dots: 1 },
      },
      edges: [
        { name: 'Library', perks: ['Who They Were: trace a creature back to the person it used to be'] },
        { name: 'Sense the Unnatural', perks: [] },
      ],
      trackers: { health: 5, willpower: 4, desperation: 1, danger: 0 },
      advantages: [
        { name: 'Contacts', dots: 3, kind: 'background', note: 'Old colleagues in the Police Scotland forensics unit' },
        { name: 'Resources', dots: 2, kind: 'background', note: 'Wedding photography, which he hates' },
        { name: 'Safe House', dots: 2, kind: 'background', note: 'His darkroom in a Partick basement' },
        { name: 'Enemy', dots: 1, kind: 'flaw', note: 'A detective inspector who thinks he tampers with evidence' },
        { name: 'Dark Secret', dots: 1, kind: 'flaw', note: 'He kept negatives from a case that was officially closed' },
      ],
      convictions: [
        { conviction: 'The truth gets told, whatever it costs.', touchstone: 'His sister Fiona, a nurse who thinks he needs therapy' },
        { conviction: 'Never let a victim become a statistic.', touchstone: 'Maggie Doyle, mother of the girl in the photographs' },
      ],
      biography: {
        born: '1991-02-27',
        turned: '2021-09-14',
        appearance: 'Swept-back grey-streaked hair, a red tartan flannel coat, a scarf, and a camera on a worn strap.',
        features: 'Chews the inside of his cheek while he thinks.',
        history:
          'Dez photographed bodies for Police Scotland for six years. Then one came back through the morgue doors without its blood and smiled at him. The report called it a mix-up. He kept the negatives, quit, and started pinning photographs to a wall. That wall became the Kelvin Street Cell’s evidence board.',
      },
    },
  },
  {
    key: 'htr-father-ruiz',
    game: 'hunter',
    sort: 2,
    name: 'Father Ruiz',
    faction: 'Faithful',
    portrait: '/portraits/hunter-priest.webp',
    summary: 'A parish priest who saw what lived in the bell tower. His Drive is Atonement, and he has a lot to atone for.',
    sheet: {
      profile: {
        name: 'Father Tomás Ruiz',
        concept: 'Parish priest with a sin to answer for',
        chronicle: 'Glasgow by Night',
        cell: 'The Kelvin Street Cell',
        creed: 'Faithful',
        drive: 'Atonement',
        ambition: 'Cleanse St Mungo’s bell tower of the thing he let in.',
        desire: 'To hear one confession that isn’t his own.',
      },
      attributes: { Strength: 2, Dexterity: 2, Stamina: 2, Charisma: 3, Manipulation: 1, Composure: 3, Intelligence: 3, Wits: 2, Resolve: 4 },
      skills: {
        Occult: { dots: 3, specialty: 'Exorcism' },
        Academics: { dots: 3, specialty: 'Theology' },
        Insight: { dots: 3, specialty: 'Confession' },
        Persuasion: { dots: 2 },
        Medicine: { dots: 2 },
        Etiquette: { dots: 2 },
        Leadership: { dots: 2 },
        Melee: { dots: 2 },
        Athletics: { dots: 1 },
        Drive: { dots: 1 },
        Awareness: { dots: 1 },
        Investigation: { dots: 1 },
        Politics: { dots: 1 },
        Intimidation: { dots: 1 },
        Performance: { dots: 1 },
      },
      edges: [
        { name: 'Repel the Unnatural', perks: [] },
        { name: 'Library', perks: ['The diocesan archive: centuries of records on what hid in Glasgow’s churches'] },
      ],
      trackers: { health: 5, willpower: 7, desperation: 1, danger: 0 },
      advantages: [
        { name: 'Allies', dots: 2, kind: 'background', note: 'The faithful of his parish' },
        { name: 'Contacts', dots: 2, kind: 'background', note: 'A canon at the archdiocese' },
        { name: 'Safe House', dots: 2, kind: 'background', note: 'The rectory cellar, consecrated twice' },
        { name: 'Resources', dots: 1, kind: 'background', note: 'A priest’s stipend' },
        { name: 'Dark Secret', dots: 1, kind: 'flaw', note: 'He gave the bell-tower creature sanctuary, and people died' },
        { name: 'Enemy', dots: 1, kind: 'flaw', note: 'The thing in the bell tower remembers him' },
      ],
      convictions: [
        { conviction: 'No one is beyond saving, except what lives in the tower.', touchstone: 'Mrs Agnelli, who arranges the flowers every Sunday' },
        { conviction: 'Protect the flock before yourself.', touchstone: 'Alfie, the altar boy who still trusts him' },
      ],
      biography: {
        born: '1962-05-08',
        turned: '2019-12-24',
        appearance: 'Heavyset, thinning white hair, a brown leather jacket over his clerical collar, and a red scarf.',
        features: 'Carries a rosary worn smooth on one side.',
        history:
          'Father Ruiz came to Glasgow from Seville in the nineties. On Christmas Eve in 2019 he opened the church to a stranger who asked for sanctuary, and the stranger never left the bell tower. Two parishioners were found drained that winter. He does not ask to be forgiven. He asks only to finish it.',
      },
    },
  },
  {
    key: 'htr-vesna-kovac',
    game: 'hunter',
    sort: 3,
    name: 'Vesna Kovač',
    faction: 'Underground',
    portrait: '/portraits/hunter-vesna.webp',
    summary: 'Runs the cell’s burner phones, safehouses and forged papers. Hunts the thing that took her brother.',
    sheet: {
      profile: {
        name: 'Vesna Kovač',
        concept: 'Smuggler who keeps the cell off the grid',
        chronicle: 'Glasgow by Night',
        cell: 'The Kelvin Street Cell',
        creed: 'Underground',
        drive: 'Vengeance',
        ambition: 'Find the creature that took Luka, and end it.',
        desire: 'To sleep in the same bed twice in a row.',
      },
      attributes: { Strength: 2, Dexterity: 4, Stamina: 2, Charisma: 2, Manipulation: 3, Composure: 3, Intelligence: 2, Wits: 3, Resolve: 1 },
      skills: {
        Streetwise: { dots: 3, specialty: 'Black market' },
        Stealth: { dots: 3 },
        Larceny: { dots: 3, specialty: 'Forged papers' },
        Subterfuge: { dots: 2 },
        Technology: { dots: 2, specialty: 'Burner phones' },
        Firearms: { dots: 2 },
        Drive: { dots: 2 },
        Awareness: { dots: 2 },
        Brawl: { dots: 1 },
        Melee: { dots: 1 },
        Athletics: { dots: 1 },
        Insight: { dots: 1 },
        Persuasion: { dots: 1 },
        Intimidation: { dots: 1 },
        Medicine: { dots: 1 },
      },
      edges: [
        { name: 'Improvised Gear', perks: [] },
        { name: 'Global Access', perks: ['Papers that survive close inspection'] },
      ],
      trackers: { health: 5, willpower: 4, desperation: 1, danger: 0 },
      advantages: [
        { name: 'Safe House', dots: 3, kind: 'background', note: 'Three flats under three names: Govan, Dennistoun, Maryhill' },
        { name: 'Contacts', dots: 2, kind: 'background', note: 'Smugglers on the Clyde docks' },
        { name: 'Resources', dots: 1, kind: 'background', note: 'Cash, never a bank' },
        { name: 'Alternate Identity', dots: 1, kind: 'background', note: 'Vera Kowalski, cleaner' },
        { name: 'Enemy', dots: 1, kind: 'flaw', note: 'A gangster she owes for her first set of papers' },
        { name: 'Addiction', dots: 1, kind: 'flaw', note: 'Cigarettes, one after another' },
      ],
      convictions: [
        { conviction: 'Leave no one behind who can still be saved.', touchstone: 'Mira, the girl she smuggled out of a blood farm' },
        { conviction: 'Never trust anything that doesn’t breathe.', touchstone: 'Her mother in Split, who still waits for Luka' },
      ],
      biography: {
        born: '1994-07-11',
        turned: '2020-03-02',
        appearance: 'Dark hair pulled back, a heavy scarf, rings and an ear full of piercings, and a cigarette always burning.',
        features: 'Never sits facing away from a door.',
        history:
          'Vesna and her brother Luka came to Glasgow on a container ship and forged papers. Luka took a job at a nightclub, and one night he walked out with the owner and never came back. The police shrugged. Vesna didn’t. She knows how to disappear, how to move people and how to get anything through customs, and now the cell uses all of it.',
      },
    },
  },
];
