import type { Starter } from '../sheets/types';

// W5 character creation: attributes 4/3/3/3/2/2/2/2/1; a skill distribution
// and three specialties; 7 dots of advantages and 2 of flaws; 3 Renown (max 2
// in any one); three Gifts: one Native, one Auspice, one Tribe, each needing
// at least one dot of its Renown; Health = Stamina + 3, Willpower =
// Composure + Resolve; Rage starts at 1, Harano and Hauglosk at 0.

export const WEREWOLVES: Starter[] = [
  {
    key: 'wta-grey-fang',
    game: 'werewolf',
    sort: 1,
    name: 'Grey-Fang',
    faction: 'Red Talons',
    portrait: '/portraits/garou-crinos.webp',
    summary: 'An Ahroun who stopped counting the hunters he has buried. Speaks rarely, and only to the pack.',
    sheet: {
      profile: {
        name: 'Grey-Fang',
        concept: 'Wolf-born warrior of the high fells',
        chronicle: 'Glasgow by Night',
        pack: 'The Rail-Yard Howlers',
        patron: 'Griffin',
        tribe: 'Red Talons',
        auspice: 'Ahroun',
        ambition: 'Drive Endron’s survey teams out of the Campsie Fells.',
        desire: 'To run with the wolves of his birth one more time.',
        breed: 'Lupus',
      },
      attributes: { Strength: 4, Dexterity: 3, Stamina: 3, Charisma: 1, Manipulation: 2, Composure: 2, Intelligence: 2, Wits: 3, Resolve: 2 },
      skills: {
        Brawl: { dots: 3, specialty: 'Tackles' },
        Survival: { dots: 3, specialty: 'Tracking' },
        Athletics: { dots: 3 },
        Stealth: { dots: 2 },
        Awareness: { dots: 2 },
        Intimidation: { dots: 2, specialty: 'Snarling' },
        Insight: { dots: 2 },
        'Animal Ken': { dots: 2 },
        Melee: { dots: 1 },
        Investigation: { dots: 1 },
        Occult: { dots: 1 },
        Streetwise: { dots: 1 },
        Medicine: { dots: 1 },
        Leadership: { dots: 1 },
        Etiquette: { dots: 1 },
      },
      renown: { glory: 1, honor: 2, wisdom: 0 },
      gifts: [
        { name: 'Staredown', source: 'Native', renown: 'Honor' },
        { name: 'Razor Claws', source: 'Auspice', renown: 'Glory' },
        { name: 'Hidden Killer', source: 'Tribe', renown: 'Honor' },
      ],
      rites: [],
      trackers: { health: 6, willpower: 4, rage: 1, harano: 0, hauglosk: 0 },
      advantages: [
        { name: 'Allies', dots: 3, kind: 'background', note: 'The wolf pack of the Campsie Fells' },
        { name: 'Haven', dots: 2, kind: 'background', note: 'A den under a fallen larch' },
        { name: 'Mask', dots: 1, kind: 'background', note: '“Greg Fang”, a drifter with no fixed address' },
        { name: 'Contacts', dots: 1, kind: 'background', note: 'A ranger who looks the other way' },
        { name: 'Illiterate', dots: 1, kind: 'flaw', note: 'Wolf-born; human letters mean nothing to him' },
        { name: 'Enemy', dots: 1, kind: 'flaw', note: 'An Endron security contractor who lost an arm to him' },
      ],
      convictions: [
        { conviction: 'The pack eats before I do.', touchstone: 'Ailsa Reid, the ranger who once set him free from a snare' },
        { conviction: 'No hunter who harms a cub walks away.', touchstone: 'The grey she-wolf who raised him' },
      ],
      biography: {
        born: '2014-04-02',
        turned: '2016-10-17',
        appearance: 'In war form a gaunt, bristling giant with a muzzle full of broken teeth. As a man, wiry and grey-haired, with eyes that never quite settle.',
        features: 'A leather cord of hunters’ teeth around his neck.',
        history:
          'Born to a wolf pack the Garou kept hidden in the fells, Grey-Fang underwent the First Change when hunters gunned down his litter-mates. The Red Talons took him in and taught him that humans would end the wild. The Rail-Yard Howlers taught him that some of them are worth protecting. He has not decided which lesson is true.',
      },
    },
  },
  {
    key: 'wta-rosa-vex',
    game: 'werewolf',
    sort: 2,
    name: 'Rosa "Static" Vex',
    faction: 'Glass Walkers',
    portrait: '/portraits/garou-punk.webp',
    summary: 'A Ragabash who hacks Endron payrolls for fun and spirit-talks the city grid for the pack.',
    sheet: {
      profile: {
        name: 'Rosa “Static” Vex',
        concept: 'Hacker trickster of the city grid',
        chronicle: 'Glasgow by Night',
        pack: 'The Rail-Yard Howlers',
        patron: 'Cockroach',
        tribe: 'Glass Walkers',
        auspice: 'Ragabash',
        ambition: 'Expose Endron’s Glasgow projects on every screen in the city.',
        desire: 'To be the one who gets away with it, again.',
        breed: 'Homid',
      },
      attributes: { Strength: 2, Dexterity: 3, Stamina: 2, Charisma: 2, Manipulation: 3, Composure: 1, Intelligence: 3, Wits: 4, Resolve: 2 },
      skills: {
        Technology: { dots: 4, specialty: 'Hacking' },
        Larceny: { dots: 3, specialty: 'Security systems' },
        Subterfuge: { dots: 3, specialty: 'Impersonation' },
        Streetwise: { dots: 3 },
        Stealth: { dots: 2 },
        Investigation: { dots: 2 },
        Finance: { dots: 2 },
        Brawl: { dots: 1 },
        Firearms: { dots: 1 },
        Occult: { dots: 1 },
      },
      renown: { glory: 1, honor: 0, wisdom: 2 },
      gifts: [
        { name: 'Penumbral Senses', source: 'Native', renown: 'Wisdom' },
        { name: 'Gremlins', source: 'Auspice', renown: 'Glory' },
        { name: 'Spider’s Song', source: 'Tribe', renown: 'Wisdom' },
      ],
      rites: [],
      trackers: { health: 5, willpower: 3, rage: 1, harano: 0, hauglosk: 0 },
      advantages: [
        { name: 'Contacts', dots: 3, kind: 'background', note: 'Hackers, a phone-shop fence and a bored IT admin at Endron' },
        { name: 'Resources', dots: 2, kind: 'background', note: 'Freelance security “testing”' },
        { name: 'Haven', dots: 1, kind: 'background', note: 'A server closet in a squatted office block' },
        { name: 'Mask', dots: 1, kind: 'background', note: 'Six online identities and one real one' },
        { name: 'Enemy', dots: 1, kind: 'flaw', note: 'Endron’s cyber-security team' },
        { name: 'Addiction', dots: 1, kind: 'flaw', note: 'Energy drinks; without them she shakes' },
      ],
      convictions: [
        { conviction: 'Every lock deserves to be picked.', touchstone: 'Dev Okafor, her flatmate from her uni days' },
        { conviction: 'Never leave a packmate in the dark.', touchstone: 'Her gran in Govan, who still calls her Rosie' },
      ],
      biography: {
        born: '1999-08-22',
        turned: '2016-05-03',
        appearance: 'Bleached hair with a red streak, a pale grey complexion, tattoos and chains, and a stack of keycards on a lanyard.',
        features: 'Lights flicker when she is angry.',
        history:
          'Rosa’s First Change hit her in the middle of a sixth-year computing exam. The Glass Walkers found her before the police did and taught her that the city has spirits too, living in its cables and signals. She joined the Howlers after hacking their caern’s security system on a dare, and has been their eyes on Endron ever since.',
      },
    },
  },
  {
    key: 'wta-old-tom-marrow',
    game: 'werewolf',
    sort: 3,
    name: 'Old Tom Marrow',
    faction: 'Bone Gnawers',
    portrait: '/portraits/garou-drifter.webp',
    summary: 'A Galliard who sings the forgotten caerns of the rail yards. Knows every stray by name.',
    sheet: {
      profile: {
        name: 'Old Tom Marrow',
        concept: 'Busker, storyteller and keeper of the rail-yard caern',
        chronicle: 'Glasgow by Night',
        pack: 'The Rail-Yard Howlers',
        patron: 'Rat',
        tribe: 'Bone Gnawers',
        auspice: 'Galliard',
        ambition: 'Wake the old caern under Cowlairs before the developers pour concrete on it.',
        desire: 'A dry place to sleep and an audience who listens.',
        breed: 'Homid',
      },
      attributes: { Strength: 2, Dexterity: 2, Stamina: 3, Charisma: 4, Manipulation: 2, Composure: 3, Intelligence: 2, Wits: 3, Resolve: 1 },
      skills: {
        Performance: { dots: 3, specialty: 'Ballads' },
        Streetwise: { dots: 2, specialty: 'Rail yards' },
        Survival: { dots: 2 },
        'Animal Ken': { dots: 2, specialty: 'Stray dogs' },
        Persuasion: { dots: 2 },
        Insight: { dots: 2 },
        Occult: { dots: 2 },
        Awareness: { dots: 2 },
        Brawl: { dots: 2 },
        Athletics: { dots: 1 },
        Stealth: { dots: 1 },
        Larceny: { dots: 1 },
        Drive: { dots: 1 },
        Etiquette: { dots: 1 },
        Leadership: { dots: 1 },
        Subterfuge: { dots: 1 },
        Medicine: { dots: 1 },
        Academics: { dots: 1 },
        Melee: { dots: 1 },
      },
      renown: { glory: 0, honor: 1, wisdom: 2 },
      gifts: [
        { name: 'The Howl Carries', source: 'Native', renown: 'Wisdom' },
        { name: 'Howl of Assembly', source: 'Auspice', renown: 'Honor' },
        { name: 'Blissful Ignorance', source: 'Tribe', renown: 'Wisdom' },
      ],
      rites: [],
      trackers: { health: 6, willpower: 4, rage: 1, harano: 0, hauglosk: 0 },
      advantages: [
        { name: 'Allies', dots: 2, kind: 'background', note: 'The rough sleepers of the rail yards' },
        { name: 'Contacts', dots: 2, kind: 'background', note: 'A soup-kitchen cook and a Network Rail signalman' },
        { name: 'Haven', dots: 1, kind: 'background', note: 'A disused signal box' },
        { name: 'Fame', dots: 1, kind: 'background', note: 'Every busker on Buchanan Street knows his songs' },
        { name: 'Mask', dots: 1, kind: 'background', note: 'Thomas Marrow, pensioner, of no fixed abode' },
        { name: 'Addiction', dots: 1, kind: 'flaw', note: 'Whisky, to quiet the old songs' },
        { name: 'Destitute', dots: 1, kind: 'flaw', note: 'Owns a fiddle, a coat and a dog' },
      ],
      convictions: [
        { conviction: 'Every story deserves to be remembered.', touchstone: 'Bonnie, his three-legged collie' },
        { conviction: 'Share the last of what you have.', touchstone: 'Sister Agnes at the Calton soup kitchen' },
      ],
      biography: {
        born: '1958-12-01',
        turned: '1972-07-19',
        appearance: 'Wild grey hair and beard, a threadbare linen jacket over a bare chest, bone charms on a string, a fiddle on his back.',
        features: 'Dogs follow him through the city without being called.',
        history:
          'Tom ran away from a children’s home at thirteen and Changed for the first time in a goods wagon at Cowlairs. The Bone Gnawers of the yards raised him on songs about caerns the city has buried. Fifty years later he is the one who remembers them all, and the Howlers are the first pack he thinks might help him wake one.',
      },
    },
  },
];
