import type { Metadata } from 'next';
import { Josefin_Slab, Josefin_Sans } from 'next/font/google';
import './globals.css';

const Jslab = Josefin_Slab({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});
const Jsans = Josefin_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={Jsans.className}>{children}</body>
    </html>
  );
}
