"""Writes app/ui/svgs/official/index.ts with a named export per SVG."""
import pathlib

ROOT = pathlib.Path('app/ui/svgs/official')
PREFIX = {
    'clans': 'Clan',
    'clan-names': 'ClanName',
    'sects': 'Sect',
    'disciplines': 'Discipline',
    'dice': 'Dice',
    'logos': 'Logo',
}

lines = [
    '// Generated by scripts/convert-brand-svgs.sh from the official Dark Pack assets.',
    '// Do not edit by hand.',
    '',
]
for folder, prefix in PREFIX.items():
    for path in sorted((ROOT / folder).glob('*.svg')):
        name = prefix + ''.join(part.capitalize() for part in path.stem.split('-'))
        lines.append(f"export {{ default as {name} }} from './{folder}/{path.name}';")
    lines.append('')
(ROOT / 'index.ts').write_text('\n'.join(lines))
